apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 764522415783.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 764522415783.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: b2243c36
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
